[package]
name = "rusttracer"
version = "0.1.0"
authors = ["Tanishq Dubey <tdubey@clearstreet.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
